import os
import sys
import shutil
import logging
import torchaudio
import soundfile as sf
from .config import DEMUCS_MODEL, DEMUCS_DEVICE

logger = logging.getLogger(__name__)

# Monkey-patch torchaudio.save using soundfile to prevent TorchCodec DLL load errors on Windows/Python 3.14
def patched_save(uri, src, sample_rate=None, **kwargs):
    """Saves PyTorch tensor to audio file using SoundFile library backend."""
    # soundfile expects data: (num_frames, num_channels)
    # torchaudio tensors are (num_channels, num_frames)
    data = src.numpy()
    if len(data.shape) > 1:
        data = data.T
        
    sr = sample_rate or kwargs.get('sample_rate')
    if sr is None:
        raise ValueError("sample_rate must be provided to save audio")
        
    sf.write(uri, data, sr)

# Apply the patch immediately upon module import
torchaudio.save = patched_save
logger.info("Monkey-patched torchaudio.save with soundfile wrapper successfully.")


class VocalSeparator:
    """Isolates vocals from accompaniment/instrumentals in an audio file using Demucs programmatically."""

    @staticmethod
    def separate(audio_path: str) -> tuple[str, str]:
        """
        Separates vocals and instrumentals from the input audio file.
        
        Args:
            audio_path: Path to the input audio file.
            
        Returns:
            A tuple of (vocals_path, instrumental_path) pointing to the generated WAV files.
        """
        if not os.path.exists(audio_path):
            raise FileNotFoundError(f"Audio file to separate not found: {audio_path}")

        logger.info("=" * 50)
        logger.info(f"Separating audio source using Demucs model '{DEMUCS_MODEL}'...")
        logger.info(f"Input audio: {audio_path}")

        # Get target paths (same directory as input audio)
        audio_dir = os.path.dirname(os.path.abspath(audio_path))
        base_name = os.path.splitext(os.path.basename(audio_path))[0]
        
        vocals_output = os.path.join(audio_dir, "vocals.wav")
        instrumental_output = os.path.join(audio_dir, "instrumental.wav")
        
        # Temp output dir for Demucs execution
        temp_out_dir = os.path.join(audio_dir, "temp_demucs_out")
        
        # Set up sys.argv to pass options to Demucs programmatically
        old_argv = sys.argv
        sys.argv = [
            "demucs",
            "--two-stems=vocals",
            "-n", DEMUCS_MODEL,
            "-o", temp_out_dir,
            audio_path
        ]
        
        if DEMUCS_DEVICE == "cuda":
            sys.argv.extend(["-d", "cuda"])
        else:
            sys.argv.extend(["-d", "cpu"])

        logger.info(f"Executing programmatic Demucs: {' '.join(sys.argv)}")
        
        try:
            from demucs import separate
            separate.main()
        except Exception as e:
            logger.error(f"Demucs separation failed: {e}")
            raise RuntimeError(f"Vocal separation failed: {e}") from e
        finally:
            # Restore original sys.argv
            sys.argv = old_argv

        # Locate the output file paths generated by Demucs
        # Structure: <temp_out_dir>/<model_name>/<base_name>/vocals.wav and no_vocals.wav
        model_out_dir = os.path.join(temp_out_dir, DEMUCS_MODEL, base_name)
        vocals_source = os.path.join(model_out_dir, "vocals.wav")
        no_vocals_source = os.path.join(model_out_dir, "no_vocals.wav")
        
        # Fallback search if Demucs used a different file format (e.g. .mp3)
        if not os.path.exists(vocals_source):
            if os.path.exists(model_out_dir):
                files = os.listdir(model_out_dir)
                for f in files:
                    if f.startswith("vocals"):
                        vocals_source = os.path.join(model_out_dir, f)
                    elif f.startswith("no_vocals"):
                        no_vocals_source = os.path.join(model_out_dir, f)

        if not os.path.exists(vocals_source) or not os.path.exists(no_vocals_source):
            raise RuntimeError(f"Demucs output files not found in expected path: {model_out_dir}")

        # Move/copy files to final target names
        shutil.copy2(vocals_source, vocals_output)
        shutil.copy2(no_vocals_source, instrumental_output)
        
        # Cleanup temporary Demucs folder
        try:
            shutil.rmtree(temp_out_dir)
        except Exception as cleanup_err:
            logger.warning(f"Could not clean up temp Demucs folder {temp_out_dir}: {cleanup_err}")

        logger.info("Vocal separation complete.")
        logger.info(f"Isolated Vocals: {vocals_output}")
        logger.info(f"Isolated Instrumentals: {instrumental_output}")
        logger.info("=" * 50)
        
        return vocals_output, instrumental_output
